name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  # Trigger on version tags
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for tags

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./test/...

    - name: Get Version
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        else
          echo "version=latest" >> $GITHUB_OUTPUT
        fi

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update pkg.go.dev
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        VERSION=${{ steps.get_version.outputs.version }}
        go list -m github.com/zaluty/gobench@${VERSION}